### PR TITLE
Update API for python 3.14.

### PR DESCRIPTION
**Pull request by poweron0102**
Update piculet.py because the find_loader function was deprecated in Python 3.4 and does no work in python 3.14.
Needs to be used with the previous pull request about the python 3.14 update (https://github.com/cinemagoer/cinemagoer/pull/543).

### CODE REVIEW

**Comment by alberanid** [comment]
thanks for the patch.

I'm not familiar with the internals of piculet, so I tag @uyar 

I notice that this PR introduces a lot of changes, and currently it also breaks the test suite:

```sh
$ uv run pytest
warning: The `requires-python` specifier (`~=3.10`) in `cinemagoer` uses the tilde specifier (`~=`) without a patch version. This will be interpreted as `>=3.10, <4`. Did you mean `~=3.10.0` to constrain the version as `>=3.10.0, <3.11`? We recommend only using the tilde specifier with a patch version to avoid ambiguity.
ImportError while loading conftest '/home/da/git/cinemagoer/tests/conftest.py'.
tests/conftest.py:8: in <module>
    from imdb.parser.http import IMDbURLopener
imdb/parser/http/__init__.py:42: in <module>
    from . import (
imdb/parser/http/searchMovieAdvancedParser.py:95: in <module>
    class DOMHTMLSearchMovieAdvancedParser(DOMParserBase):
imdb/parser/http/searchMovieAdvancedParser.py:126: in DOMHTMLSearchMovieAdvancedParser
    reduce=reducers.pipe_join)
E   AttributeError: 'Registry' object has no attribute 'pipe_join'

```

**Comment by poweron0102** [comment]
Sorry I didn't see it until now, but I make this changes on the version of this file from pip and it is different from the current version. 
Please do not accept this PR. 
I was seeing the current versions and the lines that I have changed is not in this version of the file anymore. 

Sorry for the confusion. 😥
